<<<<<<< HEAD
version: 2.1

executors:
  default:
    docker:
      - image: circleci/ruby:3.1-node-browsers
    working_directory: ~/app

jobs:
  build:
    executor: default
    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      # Database setup (if needed)
      # - run:
      #     name: Database setup
      #     command: |
      #       bundle exec rails db:create
      #       bundle exec rails db:schema:load
      #       bundle exec rails db:test:prepare

      # Run tests
      - run:
          name: Run tests
          command: |
            bundle exec rspec

workflows:
  version: 2
  build:
    jobs:
      - build
=======
# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/base
      - image: cimg/base:current

    # Add steps to the job
    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - say-hello
>>>>>>> main
